<?php

class PartnerRequest extends CComponent
{

	public $bookingId;
	public $bookingStatusCode;
	public $bookingStatus;
	public $cancelReasonId;
	public $cancelReasonDesc;
	public $cancellationReason;
	public $cancellationCharge;
	public $refundAmount;
	public $cancelledBy;
	public $tripEndDateTime;
	public $totalDistanceInKm;
	public $totalTimeInMins;
	public $baseFare;
	public $cgst;
	public $sgst;
	public $tollTax;
	public $totalAmount;
	public $driverName;
	public $driverMobile;
	public $cabNo;
	public $cabModel;
	public $fName;
	public $typeAction;
	public $extrakm;
	public $extraTimeCharge;
	public $extrakmCharge;
	public $extraMinutes;
	public $extraMin;
	public $extraMinCharge;
	public $cabName;
	public $pid;
	public $mmtBookingId;
	public $bkgId;
	public $tripStartTime;
	public $otp;
	public $type;
	public $odometer_start_reading;
	public $lattitude;
    public $timestamp;
    public $booking_id;
	public $longitude;
	public $tripStatus;
	public $drvId, $vhcId, $pickupdate;
	public $vctId, $vctType;
	public $faceMask, $faceMaskUrl;
	public $sanitizationKit, $sanitizationKitUrl;
	public $arogyaSetu;
    public $infographicCard,$infographicUrl;
    public $nightCharges, $nightChargesReceipt;
    public $tollCharges, $tollChargesReceipts;
    public $stateTaxCharges, $stateTaxReceipts;
    public $parkingCharges, $parkingChargesReceipts;
    public $extra_charge, $invoice_url;
    public $waitingCharge;
    public $miscellaneous;
    public $partner_reference_number;
    public $order_reference_number;
    public $communication_type;
    public $verification_type;
    public $verification_code;
    public $orderRefId;
    public $agentId;
	public $amount_remaining;
	public $message;
	public $success;
	public $amount_paid;
    public $airportEntryFee;
    public $vendorId;
	public $total_travelled_km;
	public $advanceAmount;
	public $amountToBeCollected;
	public $discount;
	public $driverAllowance;
	public $extraTollTax;
	public $extraStateTax;
	public $gst;
	public $transferzStatus;
}
