php -q /home/gcuser/public_html/cron.php onetime updateB2cAdvance
php -q /home/gcuser/public_html/cron.php booking retryFailedPaymentStatus
php -q /home/gcuser/public_html/cron.php booking relateDuplicateLead
php -q /home/gcuser/public_html/cron.php booking criticalityscore
php -q /home/gcuser/public_html/cron.php booking vendorAutoAssignStartLog
php -q /home/gcuser/public_html/cron.php booking processCustomerDetailsToOperatorEvent
php -q /home/gcuser/public_html/cron.php system updateDDSBP
#php -q /home/gcuser/public_html/cron.php onetime setMaxOut
#php -q /home/gcuser/public_html/cron.php booking processCriticalitySteps
#php -q /home/gcuser/public_html/cron.php booking cancelFbg
php -q /home/gcuser/public_html/cron.php booking notifyVendorsForPendingBookings
php -q /home/gcuser/public_html/cron.php booking canSelfAssignedBooking
php -q /home/gcuser/public_html/cron.php booking setUncommonRouteFlag
php -q /home/gcuser/public_html/cron.php booking autoMarkCompleteBooking
php -q /home/gcuser/public_html/cron.php booking executePartnerWallet
php -q /home/gcuser/public_html/cron.php notification updateJobDataDetails
php -q /home/gcuser/public_html/cron.php booking autoUnassignVendor
php -q /home/gcuser/public_html/cron.php booking processRefundEvent
php -q /home/gcuser/public_html/cron.php booking getPassengerDetails
php -q /home/gcuser/public_html/cron.php booking repushApi
php -q /home/gcuser/public_html/cron.php booking processMarkCompleteEvent
php -q /home/gcuser/public_html/cron.php system CloseAllPaymentFollowup
php -q /home/gcuser/public_html/cron.php track processNoShowCancelBooking
#php -q /home/gcuser/public_html/cron.php system getAllBookingForDemMisFire
php -q /home/gcuser/public_html/cron.php booking canbookingtestuser
php -q /home/gcuser/public_html/cron.php booking blockassignmenttestuser
php -q /home/gcuser/public_html/cron.php system MarkZoneType
php -q /home/gcuser/public_html/cron.php vendor sendDigitalAgreement
php -q /home/gcuser/public_html/cron.php vendor saveAgreement
php -q /home/gcuser/public_html/cron.php booking flexxiBookingAlert
php -q /home/gcuser/public_html/cron.php booking createPdfInvoice
php -q /home/gcuser/public_html/cron.php booking createZipFormate
#php -q /home/gcuser/public_html/cron.php booking autoCancel
#php -q /home/gcuser/public_html/cron.php pickupAlert driverMessageAlert
php -q /home/gcuser/public_html/cron.php system generateLedgerCsv
php -q /home/gcuser/public_html/cron.php track generateBookingGPXFile
php -q /home/gcuser/public_html/cron.php system AutoCloseDispatchQueue
php -q /home/gcuser/public_html/cron.php booking notifyReadyToPickup
php -q /home/gcuser/public_html/cron.php booking notifyDriverReadyToPickup
php -q /home/gcuser/public_html/cron.php booking NotifyVendorAssignCabDriver
php -q /home/gcuser/public_html/cron.php system EventNotification
php -q /home/gcuser/public_html/cron.php booking driverPushCustomEventsCBR


