php -q /home/gcuser/public_html/cron.php transaction updatePartnerBalance
php -q /home/gcuser/public_html/cron.php pickupAlert driverNotificationAlert
php -q /home/gcuser/public_html/cron.php booking smartmatch
php -q /home/gcuser/public_html/cron.php booking sendAdvanceReminderSMS
php -q /home/gcuser/public_html/cron.php booking sendQuoteExpiryReminderToCustomer
php -q /home/gcuser/public_html/cron.php vendor updateOutstanding
php -q /home/gcuser/public_html/cron.php booking flexxiAutoMatch
#php -q /home/gcuser/public_html/cron.php booking quotedToUnverified
php -q /home/gcuser/public_html/cron.php system updateCustomer
php -q /home/gcuser/public_html/cron.php transaction autoRefundAgainstCancellation
#php -q /home/gcuser/public_html/cron.php booking cancelFbg
php -q /home/gcuser/public_html/cron.php system updateShiftTimeOver
php -q /home/gcuser/public_html/cron.php agent updateBookingMessages
php -q /home/gcuser/public_html/cron.php agent updateBookingPrefForEMT
php -q /home/gcuser/public_html/cron.php booking sendMessagesToLatestRideCompleted
#php -q /home/gcuser/public_html/cron.php driver sendDriverAppLink
#php -q /home/gcuser/public_html/cron.php city TopCitiesByBookingCount
#php -q /home/gcuser/public_html/cron.php booking FetchBookingStatsHourly
#php -q /home/gcuser/public_html/cron.php system LocationStatsHourly
#php -q /home/gcuser/public_html/cron.php system AutoVendorApprovalOnInventoryShortage
php -q /home/gcuser/public_html/cron.php system sendCabDriverDetailsToCustomer
php -q /home/gcuser/public_html/cron.php system AutoTripStartUpperTier
php -q /home/gcuser/public_html/cron.php system MarkLeadClose
php -q /home/gcuser/public_html/cron.php system RatePerKilomter
#php -q /home/gcuser/public_html/cron.php system AutoFurCSA
php -q /home/gcuser/public_html/cron.php booking MarkALLZoneType
php -q /home/gcuser/public_html/cron.php sync uploadQrDocs
php -q /home/gcuser/public_html/cron.php sync UploadCallBackDocs
php -q /home/gcuser/public_html/cron.php booking AutoActivateManualTrigger
#php -q /home/gcuser/public_html/cron.php onetime updateCriticalTripAmountNew
php -q /home/gcuser/public_html/cron.php system AutoCloseVendorAssignedFollowup
php -q /home/gcuser/public_html/cron.php booking CustomerOngoingTrip 
#php -q /home/gcuser/public_html/cron.php system archiveSingle