php -q /home/gcuser/public_html/cron.php booking updateTransferzBookings
php -q /home/gcuser/public_html/cron.php booking updateStatus
php -q /home/gcuser/public_html/cron.php booking processPartnerPendingAdvance
php -q /home/gcuser/public_html/cron.php booking updateBalancebyBookingid
php -q /home/gcuser/public_html/cron.php onetime updateMaxAllowableVA
php -q /home/gcuser/public_html/cron.php onetime setMaxOut
php -q /home/gcuser/public_html/cron.php booking processCriticalitySteps
php -q /home/gcuser/public_html/cron.php driver updateLastLocationToMMT
php -q /home/gcuser/public_html/cron.php driver UpdateLastLocationToSpicejet
php -q /home/gcuser/public_html/cron.php booking cancelExpiredGozoNow
php -q /home/gcuser/public_html/cron.php booking getScheduleBookingForConfirmMessages
php -q /home/gcuser/public_html/cron.php notification sendBroadcastNotification
php -q /home/gcuser/public_html/cron.php track processPostSyncDriverAppEvents
#php -q /home/gcuser/public_html/cron.php oneTime RatePerKilomter
#php -q /home/gcuser/public_html/cron.php booking sendvendorreq
#php -q /home/gcuser/public_html/cron.php booking notifyBVR
php -q /home/gcuser/public_html/cron.php onetime updateUserQRCode
php -q /home/gcuser/public_html/cron.php booking updateSmtScore
php -q /home/gcuser/public_html/cron.php system LastMinBooking
php -q /home/gcuser/public_html/cron.php vendor NotifyGnowSnoozeVnd
php -q /home/gcuser/public_html/cron.php booking ProcessScheduledEvents
#php -q /home/gcuser/public_html/cron.php onetime archiveBackup
#php -q /home/gcuser/public_html/cron.php system ProcessQrCode
php -q /home/gcuser/public_html/cron.php booking unverifiedAutoCancel
php -q /home/gcuser/public_html/cron.php system processMails