<table align="center" style="color: #000; font-size: 14px; font-family: 'Arial'; line-height: 18px;word-wrap: break-word;
	margin: 0 auto 20px auto;">
<tr>
<td>
<?php
$setPasswordInstruction = '';

$msg = "Dear ".$arr['userName'].",".
 
"<p>Welcome to Gozocabs! We are delighted to have you as a new user and look forward to providing you with our exceptional services. To get started, we have generated your account credentials and are sharing them with you in this email.</p>".
 
"<p>Please find below your account login details: </p> ".
 
"<p style='margin-bottom:0;'>Username: <b> ".$arr['userName'].".</b></p>".
"<p style='margin-top:0;'>Password: " .$arr['password']."</p>".

"<p style='margin-bottom:0;'>We recommend that you log in to your account using the provided credentials and change your password to something more personalized and secure. To do so, please follow these steps:</p>".
 
"<br><p style='margin-top:0;'>Visit our website at <a href='http://www.aaocab.com/'>http://www.aaocab.com/</a></p>";

if($arr['isAutoGeneratedPass'])
{
	$setPasswordInstruction = "<p style='margin-top:0;'>Click on the 'Login' or 'Sign In' button.</p>".
			"<p style='margin-top:0;'>Enter your username and the provided password. </p>".

			"<p style='margin-top:0;'>Navigate to your account settings or profile section.</p>". 

			"<p style='margin-top:0;'>Locate the 'Change Password' or similar option.</p>". 

			"<p style='margin-bottom:0;'>Follow the instructions to set a new password of your choice. Remember to choose a strong password that includes a combination of uppercase and lowercase letters, numbers, and special characters. </p>".
			
			"<p style='margin-bottom:0;'>Please note that your account contains sensitive and confidential information, so it is crucial to keep your login credentials secure and not share them with anyone else. </p>";
}

$loginProcess = "<p style='margin-bottom:0;'>If you encounter any issues or need assistance during the login process, please feel free to contact our support team at info@aaocab.com. We are here to help you and ensure a smooth onboarding experience. </p>".
 
"<p style='margin-bottom:0;'>Once again, welcome to Gozocabs. We are excited to have you on board, and we are confident that our services will meet and exceed your expectations. Should you have any questions, feedback, or require further assistance, please do not hesitate to reach out to us. </p>".

 "<br><p style='margin-top:0;'>Thank you for choosing Gozocabs, and we look forward to serving you!</p>".
 
"<p>Best regards, <br>Team Gozo </p>";

echo $msg. $setPasswordInstruction . $loginProcess;?>
</td>
</tr>
</table>







