<?php

return
		array(

			'c/<qr_code:\S[^\/\?]+>'														 => 'index/QRCode/',
			'book-cab'																						 => 'booking/bkgType/cabsegmentation/2',
			'book-cab/sclass/inter-city/airport-pickup/<cat:\d+>/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>/*'	 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/1/type/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/sclass/inter-city/airport-drop/<cat:\d+>/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>/*'		 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/1/type/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/sclass/one-way/<cat:\d+>/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'						 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/sclass/round-trip/<cat:\d+>/<fcity:\S[^\/\?]+>'										 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/2/fcity/<fcity>',
			'book-cab/sclass/round-trip/<cat:\d+>/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'					 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/sclass/multi-city/<cat:\d+>/<fcity:\S[^\/\?]+>'										 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/3/fcity/<fcity>',
			'book-cab/sclass/airport-pickup/<cat:\d+>/<fcity:\S[^\/\?]+>'									 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/4/type/1/fcity/<fcity>',
			'book-cab/sclass/airport-drop/<cat:\d+>/<tcity:\S[^\/\?]+>'										 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/4/type/2/tcity/<tcity>',
			'book-cab/sclass/daily-rental-4/<cat:\d+>/<fcity:\S[^\/\?]+>'									 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/9/fcity/<fcity>',
			'book-cab/sclass/daily-rental-8/<cat:\d+>/<fcity:\S[^\/\?]+>'									 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/10/fcity/<fcity>',
			'book-cab/sclass/daily-rental-12/<cat:\d+>/<fcity:\S[^\/\?]+>'									 => 'booking/tierQuotes/cabcategory/<cat>/bkgType/11/fcity/<fcity>',
			'book-cab/quote/inter-city/airport-pickup/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>/*'				 => 'booking/catQuotes/bkgType/1/type/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/quote/inter-city/airport-drop/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>/*'				 => 'booking/catQuotes/bkgType/1/type/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/quote/one-way/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'									 => 'booking/catQuotes/bkgType/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/quote/round-trip/<fcity:\S[^\/\?]+>'													 => 'booking/catQuotes/bkgType/2/fcity/<fcity>',
			'book-cab/quote/rid/<sessionid:\S[^\/\?]+>'													     => 'booking/catQuotes/rid/<sessionid>',
			'book-cab/quote/round-trip/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'								 => 'booking/catQuotes/bkgType/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/quote/multi-city/<fcity:\S[^\/\?]+>'													 => 'booking/catQuotes/bkgType/3/fcity/<fcity>',
			'book-cab/quote/multi-trip/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'								 => 'booking/catQuotes/bkgType/3/fcity/<fcity>/tcity/<tcity>',
			'book-cab/quote/airport-pickup/<fcity:\S[^\/\?]+>'												 => 'booking/catQuotes/bkgType/4/type/1/fcity/<fcity>',
			'book-cab/quote/airport-drop/<tcity:\S[^\/\?]+>'												 => 'booking/catQuotes/bkgType/4/type/2/tcity/<tcity>',
			'book-cab/quote/daily-rental-4/<fcity:\S[^\/\?]+>'												 => 'booking/catQuotes/bkgType/9/fcity/<fcity>',
			'book-cab/quote/daily-rental-8/<fcity:\S[^\/\?]+>'												 => 'booking/catQuotes/bkgType/10/fcity/<fcity>',
			'book-cab/quote/daily-rental-12/<fcity:\S[^\/\?]+>'												 => 'booking/catQuotes/bkgType/11/fcity/<fcity>',
			'book-cab/inter-city/airport-pickup'															 => 'booking/itinerary/bkgType/1/type/1',
			'book-cab/inter-city/airport-pickup/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>/*'					 => 'booking/itinerary/bkgType/1/type/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/inter-city/airport-pickup/<fcity:\S[^\/\?]+>/*'										 => 'booking/itinerary/bkgType/1/type/1/fcity/<fcity>',
			'book-cab/inter-city/airport-drop'																 => 'booking/itinerary/bkgType/1/type/2',
			'book-cab/inter-city/airport-drop/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>/*'						 => 'booking/itinerary/bkgType/1/type/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/inter-city/airport-drop/<tcity:\S[^\/\?]+>/*'											 => 'booking/itinerary/bkgType/1/type/2/tcity/<tcity>',
			'book-cab/intra-city'																			 => 'booking/bkgType/cabsegmentation/1',
			'book-cab/inter-city/*'																			 => 'booking/bkgType/cabsegmentation/2',
			'book-cab/one-way'																				 => 'booking/itinerary/bkgType/1',
			'book-cab/one-way/<fcity:\S[^\/\?]+>'															 => 'booking/itinerary/bkgType/1/fcity/<fcity>',
			'bknw/oneway/<fcity:\S[^\/\?]+>'																 => 'booking/itinerary/bkgType/1/fcity/<fcity>',
			'book-cab/one-way/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'										 => 'booking/itinerary/bkgType/1/fcity/<fcity>/tcity/<tcity>',
			'bknw/oneway/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'												 => 'booking/itinerary/bkgType/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/round-trip'																			 => 'booking/itinerary/bkgType/2',
			'book-cab/round-trip/<fcity:\S[^\/\?]+>'														 => 'booking/itinerary/bkgType/2/fcity/<fcity>',
			'bknw/roundtrip/<fcity:\S[^\/\?]+>'																 => 'booking/itinerary/bkgType/2/fcity/<fcity>',
			'book-cab/round-trip/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'										 => 'booking/itinerary/bkgType/2/fcity/<fcity>/tcity/<tcity>',
			'bknw/roundtrip/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'											 => 'booking/itinerary/bkgType/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/multi-city'																			 => 'booking/itinerary/bkgType/3',
			'book-cab/multi-city/<fcity:\S[^\/\?]+>'														 => 'booking/itinerary/bkgType/3/fcity/<fcity>',
			'book-cab/multi-city/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'										 => 'booking/itinerary/bkgType/3/fcity/<fcity>/tcity/<tcity>',
			'bknw/multicity/<fcity:\S[^\/\?]+>'																 => 'booking/itinerary/bkgType/3/fcity/<fcity>',
			'bknw/multitrip/<fcity:\S[^\/\?]+>'																 => 'booking/itinerary/bkgType/3/fcity/<fcity>',
			'bknw/multitrip/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'											 => 'booking/itinerary/bkgType/3/fcity/<fcity>/tcity/<tcity>',
			'bknw/airport/<fcity:\S[^\/\?]+>'																 => 'booking/itinerary/bkgType/4/fcity/<fcity>',
			'bknw/airport/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'											 => 'booking/itinerary/bkgType/4/fcity/<fcity>/tcity/<tcity>',
			'book-cab/airport-pickup'																		 => 'booking/itinerary/bkgType/4/type/1',
			'book-cab/airport-pickup/<fcity:\S[^\/\?]+>'													 => 'booking/itinerary/bkgType/4/type/1/fcity/<fcity>',
			'book-cab/airport-pickup/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'									 => 'booking/itinerary/bkgType/4/type/1/fcity/<fcity>/tcity/<tcity>',
			'book-cab/airport-drop'																			 => 'booking/itinerary/bkgType/4/type/2',
			'book-cab/airport-drop/<tcity:\S[^\/\?]+>'														 => 'booking/itinerary/bkgType/4/type/2/tcity/<tcity>',
			'book-cab/airport-drop/<fcity:\S[^\/\?]+>/<tcity:\S[^\/\?]+>'									 => 'booking/itinerary/bkgType/4/type/2/fcity/<fcity>/tcity/<tcity>',
			'book-cab/daily-rental'																			 => 'booking/itinerary/bkgType/10',
			'bknw/dayrental/<fcity:\S[^\/\?]+>'																 => 'booking/itinerary/bkgType/10/fcity/<fcity>',
			'book-cab/daily-rental/<fcity:\S[^\/\?]+>'														 => 'booking/itinerary/bkgType/10/fcity/<fcity>',
			'bknw/dayrental12/<fcity:\S[^\/\?]+>'															 => 'booking/itinerary/bkgType/11/fcity/<fcity>',
			'bknw/dayrental8/<fcity:\S[^\/\?]+>'															 => 'booking/itinerary/bkgType/10/fcity/<fcity>',
			'book-cab/dayrental4/<fcity:\S[^\/\?]+>'														 => 'booking/itinerary/bkgType/9/fcity/<fcity>',
			'bknw/dayrental4/<fcity:\S[^\/\?]+>'															 => 'booking/itinerary/bkgType/9/fcity/<fcity>',
			'book-cab/quote/<lid:\S[^\/\?]+>/<hash:\S[^\/\?]+>'												 => 'booking/catQuotes/lid/<lid>/hash/<hash>',
			'book-cab/sclass/<cat:\d+>/<lid:\S[^\/\?]+>/<hash:\S[^\/\?]+>'									 => 'booking/tierQuotes/cabcategory/<cat>/lid/<lid>/hash/<hash>',
			'book-cab/addons/<cabclass:\d+>/<lid:\S[^\/\?]+>/<hash:\S[^\/\?]+>'								 => 'booking/addons/cabclass/<cabclass>/lid/<lid>/hash/<hash>',
			'book-cab/info/<lid:\S[^\/\?]+>/<hash:\S[^\/\?]+>'												 => 'booking/address/lid/<lid>/hash/<hash>',
			'book-cab/travellerinfo/<lid:\S[^\/\?]+>/<hash:\S[^\/\?]+>'                                      => 'booking/travellercontact/lid/<lid>/hash/<hash>',
			'book-cab/travellerinfo/<lid:\S[^\/\?]+>/<hash:\S[^\/\?]+>/<dlid:\S[^\/\?]+>/<dhash:\S[^\/\?]+>'   => 'booking/travellercontact/lid/<lid>/hash/<hash>/dlid/<dlid>/dhash/<dhash>',
			'book-data/<id:\S[^\/\?]+>/<hash:\S[^\/\?]+>'													 => 'booking/review/bkgid/<id>/hash/<hash>',
			'booking/paymentreview/<id:\d+>/<hash:\S[^\/\?]+>'												 => 'booking/paymentReview',
			'pay-now/<id:\S[^\/\?]+>/<hash:\S[^\/\?]+>'														 => 'booking/paymentReview/id/<id>/hash/<hash>',
			'epass/<bkgid:\w+>/<hash:\w+>/*'																 => 'index/epass',
			'wiki/video/<video:\w+>'																		 => 'index/videoTutorial',
			'aborted/<id:\w+>'																				 => 'index/vendorAborted',
			'invite/<refcode:\w+>'																			 => 'users/signup',
			'invoice/<bkgId:\w+>/<hash:\w+>/*'																 => 'booking/invoiceCopy',
			'gznow/<id:\w+>/<hash:\w+>/*'																	 => 'booking/gozoNowShowVndList',
			'bkpn/<id:\w+>/<hash:\w+>/p/<pHash:\w+>/*'														 => 'booking/paynow',
			'bkpn/<id:\w+>/<hash:\w+>/e/<eHash:\w+>/*'														 => 'booking/paynow',
			'bkpn/<id:\w+>/<hash:\w+>/*'																	 => 'booking/paynow',
			'bknw/<id:\w+>/<hash:\w+>/<alertid:\w+>/*'														 => 'booking/address/lid/<lid>/hash/<hash>',
			'bknw/<id:\w+>/<hash:\w+>/*'																	 => 'booking/address/lid/<lid>/hash/<hash>',
			'bknw/<id:\w+>/<hash:\w+>'																		 => 'booking/address/lid/<lid>/hash/<hash>',
			//'bknw/<fromCity:\w+>/<toCity:\w+>'					 => 'booking/booknow/<fromCity>/<toCity>',
			'bknw/<tripType:\w+>/<fromCity:\w+>/<toCity:\w+>'												 => 'booking/booknow/<tripType>/<fromCity>/<toCity>',
			'shuttle/<fromCity:\w+>/<toCity:\w+>'															 => 'index/index/tripType/shuttle/fromCity/<fromCity>/toCity/<toCity>',
			'shuttle'																						 => 'index/index/tripType/shuttle',
			//'day-rental'										 => 'index/index/tripType/day-rental',
			'day-rental'																					 => 'booking/itinerary/day-rental',
			'flashsale'																						 => 'booking/flashsale',
			'message'																						 => 'index/pushNotificationRedirect',
			'airport-transfers'																				 => 'index/index/tripType/airport-transfers',
			'fbflexxishare/<id:\w+>/<hash:\w+>/*'															 => 'booking/fbflexxishare',
			'vtrip/<id:\w+>/<hash:\w+>'																		 => 'booking/verifytrip',
			//	'bkver/<id:\w+>/<hash:\w+>'							 => 'booking/verify1',
			'ucsu/<id:\w+>/<hash:\w+>'																		 => 'users/confirmsignup',
			'r/<uniqueid:\w+>'																				 => 'rating/bookingreview',
			'r/<uniqueid:\w+>&val=<val:\w+>'																 => 'rating/bookingreview',
			'get/<buv_id:\w+>'																				 => 'index/bookingRequest',
			'DND/<buv_id:\w+>'																				 => 'index/unregunsubscribe',
			'just1'																							 => 'index/flexxisale',
			'just1/<flsId:\w+>'																				 => 'index/flexxiuser',
			//'just199' => 'just1',
			'just199'																						 => 'index/flexxisale',
			'just199/<flsId:\w+>'																			 => 'index/flexxiuser',
			'vpay/<order:\w+>/*'																			 => 'voucher/checkout',
			'CP/<id:\w+>/<hash:\w+>'																		 => 'index/cplanding',
			'u/<id:\w+>/<hash:\w+>'																			 => 'booking/unverified',
			'u/<id:\w+>/<hash:\w+>/e/<eHash:\w+>/r/<rid:\w+>/*'												 => 'booking/unverified',
			'u/<id:\w+>/<hash:\w+>/e/<eHash:\w+>/*'															 => 'booking/unverified',
			'u/<id:\w+>/<hash:\w+>/p/<pHash:\w+>/*'															 => 'booking/unverified',
			'f/<id:\w+>/<hash:\w+>/e/<eHash:\w+>/*'															 => 'booking/unvFollowupCS',
			'f/<id:\w+>/<hash:\w+>/p/<pHash:\w+>/*'															 => 'booking/unvFollowupCS',
			'bkunv/<id:\w+>/<hash:\w+>'																		 => 'booking/unverified',
			'bkconfirm/<bookingId:\w+>/<hash:\w+>'															 => 'booking/reconfirm',
			'bkvendor/<id:\w+>/<hash:\w+>'																	 => 'booking/vendorpaynow',
			'bkvn/<id:\w+>/<vndId:\w+>'																		 => 'booking/vendorpay',
			'bkvn1/<tripHash:\w+>/<vndHash:\w+>'															 => 'booking/vendortrip',
			'u/<dccode:\w+>'																				 => 'drivers/uploaddocs',
			'e'																								 => 'users/sosUrl',
			'verify'																						 => 'contact/approve',
			'forgotpassword'																				 => 'users/userforgotpassword',
			'signin'																						 => 'users/signin',
			'signup'																						 => 'users/signin',
			'login'																							 => 'users/signin',
			'agentsignin'																					 => 'agent/index/index',
			'terms-GozoFLEXXI'																				 => 'index/flexxiterms',
			'payment/response?ptpid=6'																		 => 'payu/response',
			'payment/response?ptpid=3'																		 => 'paytm/response',
			//'payment/response?ptpid=4'						=> 'ebs/response',
			'payment/response?ptpid=10'																		 => 'mobikwik/response',
			'payment/response?ptpid=12'																		 => 'freecharge/response',
			'payment/response?ptpid=14'																		 => 'lazypay/response',
			'payment/response?ptpid=16'																		 => 'paynimo/response',
			'payment/response?ptpid=21&bolt=1'																 => 'razorpay/response',
			'payment/response?ptpid=23'																		 => 'easebuzz/response',
			'openings'																						 => 'index/careers',
			'opening'																						 => 'index/careers',
			'careers'																						 => 'index/careers',
			'career'																						 => 'index/careers',
			'redirect'																						 => 'index/redirect',
			'landing'																						 => 'index/landing',
			'aboutus'																						 => 'index/aboutus',
			'gozonow'																						 => 'index/gozonow',
			'widgets'																						 => 'index/widgets',
			'driver-app'																					 => 'index/DownloadDriverApp',
			'partner-app'																					 => 'index/DownloadPartnerApp',
			'refer'																							 => 'index/refer',
			'pricematch'																					 => 'index/pricematch',
			'mumbai'																						 => 'index/mumbai',
			'tchallenge'																					 => 'index/tchallenge',
			'travelhappy'																					 => 'index/travelhappy',
			'changeindia'																					 => 'index/changeindia',
			'about'																							 => 'index/aboutus',
			'bookNow'																						 => 'booking/bookNow1',
			'bknw'																							 => 'booking/bookNow1',
			'verifyPhone'																					 => 'contact/verifyPhone',
			'terms/channelpartner'																			 => 'index/channelpartner',
			'terms/appchannelpartner'																		 => 'index/appchannelpartner',
			'whygozo'																						 => 'index/whygozo',
			'refer-friend'																					 => 'index/referFriend',
			'packages'																						 => 'booking/package',
			'packages/<packageName:.*>'																		 => 'booking/package',
			'book-shuttle'																					 => 'booking/shuttle',
			'e/mff'																							 => 'booking/mff',
			'e/sunburn'																						 => 'booking/sunburn',
			'e/supersonic'																					 => 'booking/supersonic',
			'e/sulafest'																					 => 'booking/sulafest',
			'e/Nh7weekender'																				 => 'booking/Nh7weekender',
			'e/sunsplash'																					 => 'booking/sunsplash',
			'e/comic-con'																					 => 'booking/comiccon',
			'e/mood-indigo'																					 => 'booking/moodindigo',
			'e/kumbh'																						 => 'booking/kumbh',
			'atirudram2017'																					 => 'booking/atirudram2017',
			'terms'																							 => 'index/terms',
			'earn10k'																						 => 'index/earn10k',
			'faq'																							 => 'index/faqs',
			'app'																						 => 'index/app',
			'terms/doubleback'																				 => 'index/doubleback',
			'terms/doubleBackAppView'																				 => 'index/doubleBackAppView',
			'one-way-cab'																					 => 'index/onewayCabs',
			'one-way-cabs'																					 => 'index/onewayCabs',
			//'luxary-cabs'										 =>	'index/luxaryCabs',
			'Luxury-car-rental/<city:\w+>'																	 => 'index/luxaryCabs',
			'tnc'																							 => 'terms/#tnc',
			'bd'																							 => 'index/bd',
			'resetpassword'																					 => 'users/verifyandresetpassword',
			'contactus'																						 => 'index/contactus',
//			'vendor/join'																					 => 'index/joinus',
//			'join/vendor'																					 => 'index/vendorjoin',
			'vendor/join'																					 => 'index/vendorjoin',
			'local/attachnow'																				 => 'index/vendorjoin',
			'gst'																							 => 'index/gst',
			'operator/invite'																				 => 'index/operatorjoin',
//			'agent/join'																					 => 'index/joinus',
//			'join/agent'																					 => 'index/agentjoin',
			'agent/join'																					 => 'index/agentjoin',
			'corporate/join'																				 => 'index/corpjoin',
			'disclaimer'																					 => 'index/disclaimer',
			'privacy'																						 => 'index/privacy',
			'termsmd'																						 => 'index/termsmd',
			'termsvendor'																					 => 'index/termsvendor',
			'termsagent'																					 => 'index/termsagent',
			'termsvendormd'																					 => 'index/termsvendormd',
			'privacymd'																						 => 'index/privacymd',
			'win1day'																						 => 'index/Win1day',
			'rgrpt'																							 => 'xyz/mbkg',
			'ask-us-to-be-official-partner'																	 => 'index/officialPartner',
			'goFLEXXI'																						 => 'index/flexxi',
			'win1day'																						 => 'index/win1day',
			'go4Rs1'																						 => 'index/go4Rs1',
			'newsroom'																						 => 'index/newsroom',
			'GozoSHARE'																						 => 'index/share',
			'business-travel'																				 => 'index/businessTravel',
			'join-our-agent-network'																		 => 'index/joinAgentNetwork',
			'your-travel-desk'																				 => 'index/yourTravelDesk',
			'for-startups'																					 => 'index/forStartups',
			'brand-partner'																					 => 'index/brandPartner',
			'partners-testimonials'																			 => 'index/partnersTestimonials',
			'price-guarantee'																				 => 'index/priceGuarantee',
			'corp-refer'																					 => 'index/Corporate',
			'blog'																							 => 'index/blog',
			'sitemap'																						 => 'index/sitemap',
			'gozocalendar'																					 => 'index/gozocalendar',
			'contest-terms'																					 => 'index/contestTerms',
			'refer/<refcode:\w+>'																			 => 'users/FbShareTemplate',
			'sitemap.xml'																					 => 'sitemap/xml',
			'sitemap<param1:\d+>.xml'																		 => 'sitemap/xml/page/<param1>',
			'admpnl'																						 => 'admin',
			'admpnl/<_c:\w+>/<_a:\w+>/<id:\d+>'																 => 'admin/<_c>/<_a>/<id>',
			'admpnl/<_c:\w+>/<_a:\w+>/<param1:\w+>/<param2:\w+>'											 => 'admin/<_c>/<_a>/<param1>/<param2>',
			'admpnl/<_c:\w+>/<_a:\w+>'																		 => 'admin/<_c>/<_a>',
			'mffreport'																						 => 'admin/xyz/mffreport',
			'mffcab'																						 => 'admin/xyz/mffcab',
			'admpnl/<_c:\w+>'																				 => 'admin/<_c>',
			'vndsl/<id:\w+>/<hash:\w+>/*'																	 => 'users/sociallogin',
			'admpnl/report/zonewise-count'																	 => 'xyz/mbkg2',
			'vendor/attach'																					 => 'vendors/attach',
			'vendorAttach'																					 => 'vendors/attach',
			'vendor/success'																				 => 'index/Vendorjoinsuccess',
			'agent/<_c:\w+>/<_a:\w+>'																		 => 'agent/<_c>/<_a>',
			'report/<_c:\w+>/<_a:\w+>'																		 => 'report/<_c>/<_a>',
			'dct/<hash:\w+>'																				 => 'track/dcoInterested/hash/<hash>',
			'dctd/<hash:\w+>'																				 => 'track/dcoDownload/hash/<hash>',
			'vwo/<hash:\w+>'																				 => 'track/VendorWriteOff/hash/<hash>',
			'vdco/<hash:\w+>'																				 => 'track/VendorDownloadDco/hash/<hash>',
			'vrec/<hash:\w+>'																				 => 'track/VendorLoginReminder/hash/<hash>',
		) +
		['api/vendor/<controller:\w+>'														 => ['vendor/<controller>/REST.GET', 'verb' => 'GET'],
			'api/vendor/<controller:\w+>/<id:\w*>'												 => ['vendor/<controller>/REST.GET', 'verb' => 'GET'],
			'api/vendor/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['vendor/<controller>/REST.GET', 'verb' => 'GET'],
			'api/vendor/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'					 => ['vendor/<controller>/REST.GET', 'verb' => 'GET'],
			['vendor/<controller>/REST.POST', 'pattern' => 'api/vendor/<controller:\w+>', 'verb' => 'POST'],
			['vendor/<controller>/REST.POST', 'pattern' => 'api/vendor/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['vendor/<controller>/REST.POST', 'pattern' => 'api/vendor/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['vendor/<controller>/REST.POST', 'pattern' => 'api/vendor/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/cpaa/<controller:\w+>'															 => ['cpaa/<controller>/REST.GET', 'verb' => 'GET'],
			'api/cpaa/<controller:\w+>/<id:\w*>'												 => ['cpaa/<controller>/REST.GET', 'verb' => 'GET'],
			'api/cpaa/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['cpaa/<controller>/REST.GET', 'verb' => 'GET'],
			'api/cpaa/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'						 => ['cpaa/<controller>/REST.GET', 'verb' => 'GET'],
			['cpaa/<controller>/REST.POST', 'pattern' => 'api/cpaa/<controller:\w+>', 'verb' => 'POST'],
			['cpaa/<controller>/REST.POST', 'pattern' => 'api/cpaa/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['cpaa/<controller>/REST.POST', 'pattern' => 'api/cpaa/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['cpaa/<controller>/REST.POST', 'pattern' => 'api/cpaa/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/conapp/<controller:\w+>'														 => ['conapp/<controller>/REST.POST', 'verb' => 'POST'],
			'api/conapp/<controller:\w+>'														 => ['conapp/<controller>/REST.GET', 'verb' => 'GET'],
			'api/conapp/<controller:\w+>/<id:\w*>'												 => ['conapp/<controller>/REST.GET', 'verb' => 'GET'],
			'api/conapp/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['conapp/<controller>/REST.GET', 'verb' => 'GET'],
			'api/conapp/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'					 => ['conapp/<controller>/REST.GET', 'verb' => 'GET'],
			['conapp/<controller>/REST.POST', 'pattern' => 'api/conapp/<controller:\w+>', 'verb' => 'POST'],
			['conapp/<controller>/REST.POST', 'pattern' => 'api/conapp/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['conapp/<controller>/REST.POST', 'pattern' => 'api/conapp/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['conapp/<controller>/REST.POST', 'pattern' => 'api/conapp/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/driver/<controller:\w+>'														 => ['driver/<controller>/REST.GET', 'verb' => 'GET'],
			'api/driver/<controller:\w+>/<id:\w*>'												 => ['driver/<controller>/REST.GET', 'verb' => 'GET'],
			'api/driver/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['driver/<controller>/REST.GET', 'verb' => 'GET'],
			'api/driver/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'					 => ['driver/<controller>/REST.GET', 'verb' => 'GET'],
			['driver/<controller>/REST.POST', 'pattern' => 'api/driver/<controller:\w+>', 'verb' => 'POST'],
			['driver/<controller>/REST.POST', 'pattern' => 'api/driver/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['driver/<controller>/REST.POST', 'pattern' => 'api/driver/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['driver/<controller>/REST.POST', 'pattern' => 'api/driver/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/meterdown/<controller:\w+>'													 => ['meterdown/<controller>/REST.GET', 'verb' => 'GET'],
			'api/meterdown/<controller:\w+>/<id:\w*>'											 => ['meterdown/<controller>/REST.GET', 'verb' => 'GET'],
			'api/meterdown/<controller:\w+>/<id:\w*>/<param1:\w*>'								 => ['meterdown/<controller>/REST.GET', 'verb' => 'GET'],
			'api/meterdown/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'					 => ['meterdown/<controller>/REST.GET', 'verb' => 'GET'],
			['meterdown/<controller>/REST.POST', 'pattern' => 'api/meterdown/<controller:\w+>', 'verb' => 'POST'],
			['meterdown/<controller>/REST.POST', 'pattern' => 'api/meterdown/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['meterdown/<controller>/REST.POST', 'pattern' => 'api/meterdown/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['meterdown/<controller>/REST.POST', 'pattern' => 'api/meterdown/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'https://api.aaocab.com/agent/<controller:\w+>'									 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'https://api.aaocab.com/agent/<controller:\w+>'									 => ['agent/<controller>/REST.POST', 'verb' => 'POST'],
			'https://api.aaocab.com/agent/<controller:\w+>/<id:\w*>'							 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'https://api.aaocab.com/agent/<controller:\w+>/<id:\w*>'							 => ['agent/<controller>/REST.POST', 'verb' => 'POST'],
			'https://api.aaocab.com/agent/<controller:\w+>/<id:\w*>/<param1:\w*>'				 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'https://api.aaocab.com/agent/<controller:\w+>/<id:\w*>/<param1:\w*>'				 => ['agent/<controller>/REST.POST', 'verb' => 'POST'],
			'https://api.aaocab.com/agent/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>' => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'https://api.aaocab.com/agent/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>' => ['agent/<controller>/REST.POST', 'verb' => 'POST'],
			'api/agent/<controller:\w+>'														 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'api/agent/<controller:\w+>'														 => ['agent/<controller>/REST.POST', 'verb' => 'POST'],
			'api/agent/<controller:\w+>/<id:\w*>'												 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'api/agent/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			'api/agent/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'						 => ['agent/<controller>/REST.GET', 'verb' => 'GET'],
			['agent/<controller>/REST.POST', 'pattern' => 'api/agent/<controller:\w+>', 'verb' => 'POST'],
			['agent/<controller>/REST.POST', 'pattern' => 'api/agent/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['agent/<controller>/REST.POST', 'pattern' => 'api/agent/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['agent/<controller>/REST.POST', 'pattern' => 'api/agent/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/cpapi/<controller:\w+>'														 => ['cpapi/<controller>/REST.POST', 'verb' => 'POST'],
			'api/cpapi/<controller:\w+>'														 => ['cpapi/<controller>/REST.GET', 'verb' => 'GET'],
			'api/cpapi/<controller:\w+>/<id:\w*>'												 => ['cpapi/<controller>/REST.GET', 'verb' => 'GET'],
			'api/cpapi/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['cpapi/<controller>/REST.GET', 'verb' => 'GET'],
			'api/cpapi/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'						 => ['cpapi/<controller>/REST.GET', 'verb' => 'GET'],
			['cpapi/<controller>/REST.POST', 'pattern' => 'api/cpapi/<controller:\w+>', 'verb' => 'POST'],
			['cpapi/<controller>/REST.POST', 'pattern' => 'api/cpapi/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['cpapi/<controller>/REST.POST', 'pattern' => 'api/cpapi/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['cpapi/<controller>/REST.POST', 'pattern' => 'api/cpapi/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/admin/<controller:\w+>'														 => ['admin/<controller>/REST.GET', 'verb' => 'GET'],
			'api/admin/<controller:\w+>'														 => ['admin/<controller>/REST.POST', 'verb' => 'POST'],
			'api/admin/<controller:\w+>/<id:\w*>'												 => ['admin/<controller>/REST.GET', 'verb' => 'GET'],
			'api/admin/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['admin/<controller>/REST.GET', 'verb' => 'GET'],
			'api/admin/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'						 => ['admin/<controller>/REST.GET', 'verb' => 'GET'],
			['admin/<controller>/REST.POST', 'pattern' => 'api/admin/<controller:\w+>', 'verb' => 'POST'],
			['admin/<controller>/REST.POST', 'pattern' => 'api/admin/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['admin/<controller>/REST.POST', 'pattern' => 'api/admin/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['admin/<controller>/REST.POST', 'pattern' => 'api/admin/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'api/dco/<controller:\w+>'															 => ['dco/<controller>/REST.GET', 'verb' => 'GET'],
			'api/dco/<controller:\w+>'															 => ['dco/<controller>/REST.POST', 'verb' => 'POST'],
			'api/dco/<controller:\w+>/<id:\w*>'													 => ['dco/<controller>/REST.GET', 'verb' => 'GET'],
			'api/dco/<controller:\w+>/<id:\w*>/<param1:\w*>'									 => ['dco/<controller>/REST.GET', 'verb' => 'GET'],
			'api/dco/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'						 => ['dco/<controller>/REST.GET', 'verb' => 'GET'],
			['dco/<controller>/REST.POST', 'pattern' => 'api/dco/<controller:\w+>', 'verb' => 'POST'],
			['dco/<controller>/REST.POST', 'pattern' => 'api/dco/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['dco/<controller>/REST.POST', 'pattern' => 'api/dco/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['dco/<controller>/REST.POST', 'pattern' => 'api/dco/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			'<fromCity:[a-zA-Z0-9_]+>-<toCity:[a-zA-Z0-9_-]+>'									 => 'booking/redirect/route/<fromCity>-<toCity>',
			'amp/book-taxi/<route:[a-zA-Z0-9_-]+>'												 => 'booking/routes/route/<route>/amp/1',
			'book-taxi/<route:[a-zA-Z0-9_-]+>'													 => 'booking/routes/route/<route>',
			'route-rating/<route:[a-zA-Z0-9_-]+>'												 => 'booking/routerating/route/<route>',
			'amp/car-rental/<fromCity:[a-zA-Z0-9_-]+>'											 => 'index/cities/city/<fromCity>/amp/1',
			'car-rental/<fromCity:[a-zA-Z0-9_-]+>'												 => 'index/cities/city/<fromCity>',
			'city-rating/<fromCity:[a-zA-Z0-9_-]+>'												 => 'index/cityRating/city/<fromCity>',
			'tourist-cabs/<fromCity:[a-zA-Z0-9_-]+>'											 => 'index/cities/city/<fromCity>',
			'tempo-traveller-rental/<fromCity:[a-zA-Z0-9_-]+>'									 => 'index/temporoutes/city/<fromCity>',
			'amp/tempo-traveller-rental/<fromCity:[a-zA-Z0-9_-]+>'								 => 'index/temporoutes/city/<fromCity>/amp/1',
			'cheapest-oneway-rides'																 => 'Page/GoldenRoute',
			'airport-transfer/<fromCity:[a-zA-Z0-9_-]+>'										 => 'index/AirportTransfers/city/<fromCity>',
			'amp/airport-transfer/<fromCity:[a-zA-Z0-9_-]+>'									 => 'index/AirportTransfers/city/<fromCity>/amp/1',
			'amp/outstation-cabs/<fromCity:[a-zA-Z0-9_-]+>'										 => 'index/outstationroutes/city/<fromCity>/amp/1',
			'outstation-cabs/<fromCity:[a-zA-Z0-9_-]+>'											 => 'index/outstationroutes/city/<fromCity>',
			'amp/Luxury-car-rental/<city:[a-zA-Z0-9_-]+>'										 => 'index/luxaryCabs/amp/1',
			'rbac/<_c:\w+>/<_a:\w+>'															 => 'rbac/<_c>/<_a>',
			'api/<controller:\w+>'																 => ['<controller>/REST.GET', 'verb' => 'GET'],
			'api/<controller:\w+>/<id:\w*>'														 => ['<controller>/REST.GET', 'verb' => 'GET'],
			'api/<controller:\w+>/<id:\w*>/<param1:\w*>'										 => ['<controller>/REST.GET', 'verb' => 'GET'],
			'api/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>'							 => ['<controller>/REST.GET', 'verb' => 'GET'],
			['<controller>/REST.PUT', 'pattern' => 'api/<controller:\w+>/<id:\w*>', 'verb' => 'PUT'],
			['<controller>/REST.PUT', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'PUT'],
			['<controller>/REST.PUT', 'pattern' => 'api/<controller:\w*>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'PUT'],
			['<controller>/REST.DELETE', 'pattern' => 'api/<controller:\w+>/<id:\w*>', 'verb' => 'DELETE'],
			['<controller>/REST.DELETE', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'DELETE'],
			['<controller>/REST.DELETE', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'DELETE'],
			['<controller>/REST.POST', 'pattern' => 'api/<controller:\w+>', 'verb' => 'POST'],
			['<controller>/REST.POST', 'pattern' => 'api/<controller:\w+>/<id:\w+>', 'verb' => 'POST'],
			['<controller>/REST.POST', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'POST'],
			['<controller>/REST.POST', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'POST'],
			['<controller>/REST.OPTIONS', 'pattern' => 'api/<controller:\w+>', 'verb' => 'OPTIONS'],
			['<controller>/REST.OPTIONS', 'pattern' => 'api/<controller:\w+>/<id:\w+>', 'verb' => 'OPTIONS'],
			['<controller>/REST.OPTIONS', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>', 'verb' => 'OPTIONS'],
			['<controller>/REST.OPTIONS', 'pattern' => 'api/<controller:\w+>/<id:\w*>/<param1:\w*>/<param2:\w*>', 'verb' => 'OPTIONS'],
			'<controller:\w+>/<id:\d+>'															 => '<controller>/view',
			'<controller:(booking|index)>/<action:\w+>/*'										 => '<controller>/<action>',
			'<controller:\w+>/<action:\w+>/<id:\d+>'											 => '<controller>/<action>',
			'<controller:\w+>/<action:\w+>'														 => '<controller>/<action>',
			'index.php?r=<controller:\w+>/<action:\w+>'											 => '<controller>/<action>',
];
